// flow-typed signature: 0ea106fc0b2b04f79ce143d6ef7c0faf
// flow-typed version: <<STUB>>/underscore.deepclone_v^0.1.3/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'underscore.deepclone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'underscore.deepclone' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'underscore.deepclone/dist/underscore.deepclone' {
  declare module.exports: any;
}

declare module 'underscore.deepclone/dist/underscore.deepclone.min' {
  declare module.exports: any;
}

declare module 'underscore.deepclone/Gruntfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'underscore.deepclone/dist/underscore.deepclone.js' {
  declare module.exports: $Exports<'underscore.deepclone/dist/underscore.deepclone'>;
}
declare module 'underscore.deepclone/dist/underscore.deepclone.min.js' {
  declare module.exports: $Exports<'underscore.deepclone/dist/underscore.deepclone.min'>;
}
declare module 'underscore.deepclone/Gruntfile.js' {
  declare module.exports: $Exports<'underscore.deepclone/Gruntfile'>;
}
